package-name: arduinocore-zephyr-pse84
include:
    - cores
    - libraries
    - variants
    - boards.txt
    - platform.txt
    - LICENSE
    - README.md
    - post_install.sh
index-name: package_infineon_pse84_index
server:
    type: github
    owner: Infineon
    repo: ArduinoCore-zephyr